// { word: "I", board: "Home" },
export var boardList = [
  "Home",
  "Actions",
  "Chat",
  "Describe",
  "Help",
  "People",
  "Places",
  "Questions",
  "ShortWords",
  "Things",
  "Time",
];
export var wordList = [
  { word: "I", board: "Home" },
  { word: "You", board: "Home" },
  { word: "This", board: "Home" },
  { word: "That", board: "Home" },
  { word: "It", board: "Home" },
  { word: "Want", board: "Home" },
  { word: "Will", board: "Home" },
  { word: "Can", board: "Home" },
  { word: "Is", board: "Home" },
  { word: "Have", board: "Home" },
  { word: "Make", board: "Home" },
  { word: "Get", board: "Home" },
  { word: "Like", board: "Home" },
  { word: "Stop", board: "Home" },
  { word: "What", board: "Home" },
  { word: "Drink", board: "Home" },
  { word: "Help", board: "Home" },
  { word: "Need", board: "Home" },
  { word: "Put", board: "Home" },
  { word: "Who", board: "Home" },
  { word: "Eat", board: "Home" },
  { word: "Say", board: "Home" },
  { word: "Do", board: "Home" },
  { word: "Come", board: "Home" },
  { word: "Places", board: "Home" },
  { word: "Where", board: "Home" },
  { word: "Turn", board: "Home" },
  { word: "Know", board: "Home" },
  { word: "See", board: "Home" },
  { word: "In", board: "Home" },
  { word: "Out", board: "Home" },
  { word: "To", board: "Home" },
  { word: "On", board: "Home" },
  { word: "And", board: "Home" },
  { word: "The", board: "Home" },
  { word: "With", board: "Home" },
  { word: "A", board: "Home" },
  { word: "For", board: "Home" },
  { word: "More", board: "Home" },
  { word: "Not", board: "Home" },
  { word: "Some", board: "Home" },
  { word: "All", board: "Home" },
  { word: "Yes", board: "Home" },
  { word: "No", board: "Home" },
  { word: "Save", board: "Actions" },
  { word: "Take", board: "Actions" },
  { word: "Give", board: "Actions" },
  { word: "Watch", board: "Actions" },
  { word: "Call", board: "Actions" },
  { word: "Wear", board: "Actions" },
  { word: "Let", board: "Actions" },
  { word: "Choose", board: "Actions" },
  { word: "Travel", board: "Actions" },
  { word: "Tell", board: "Actions" },
  { word: "Talk", board: "Actions" },
  { word: "Work", board: "Actions" },
  { word: "Change", board: "Actions" },
  { word: "Find", board: "Actions" },
  { word: "Hope", board: "Actions" },
  { word: "Show", board: "Actions" },
  { word: "Rest", board: "Actions" },
  { word: "Open", board: "Actions" },
  { word: "Ask", board: "Actions" },
  { word: "Answer", board: "Actions" },
  { word: "Look", board: "Actions" },
  { word: "Wear", board: "Actions" },
  { word: "Start", board: "Actions" },
  { word: "Meet", board: "Actions" },
  { word: "Run", board: "Actions" },
  { word: "Walk", board: "Actions" },
  { word: "Close", board: "Actions" },
  { word: "Buy", board: "Actions" },
  { word: "Read", board: "Actions" },
  { word: "Love", board: "Actions" },
  { word: "Think", board: "Actions" },
  { word: "Finish", board: "Actions" },
  { word: "Try", board: "Actions" },
  { word: "Sleep", board: "Actions" },
  { word: "Move", board: "Actions" },
  { word: "Turn", board: "Actions" },
  { word: "Feel", board: "Actions" },
  { word: "Cut", board: "Actions" },
  { word: "Pull", board: "Actions" },
  { word: "Push", board: "Actions" },
  { word: "Listen", board: "Actions" },
  { word: "Sit", board: "Actions" },
  { word: "Hurt", board: "Actions" },
  { word: "Bring", board: "Actions" },
  { word: "Use", board: "Actions" },
  { word: "Stay", board: "Actions" },
  { word: "Leave", board: "Actions" },
  { word: "Use", board: "Actions" },
  { word: "Hello", board: "Chat" },
  { word: "Goodbye", board: "Chat" },
  { word: "Like", board: "Chat" },
  { word: "Dislike", board: "Chat" },
  { word: "Hate", board: "Chat" },
  { word: "Thank You", board: "Chat" },
  { word: "No Problem", board: "Chat" },
  { word: "Please", board: "Chat" },
  { word: "Sorry", board: "Chat" },
  { word: "Ok", board: "Chat" },
  { word: "Wait A Minute", board: "Chat" },
  { word: "Maybe", board: "Chat" },
  { word: "Leave Me Alone", board: "Chat" },
  { word: "Later", board: "Chat" },
  { word: "Now", board: "Chat" },
  { word: "Close", board: "Describe" },
  { word: "Big", board: "Describe" },
  { word: "Little", board: "Describe" },
  { word: "Better", board: "Describe" },
  { word: "Worse", board: "Describe" },
  { word: "Fast", board: "Describe" },
  { word: "Slow", board: "Describe" },
  { word: "Near", board: "Describe" },
  { word: "Far", board: "Describe" },
  { word: "Good", board: "Describe" },
  { word: "Bad", board: "Describe" },
  { word: "Cold", board: "Describe" },
  { word: "Hot", board: "Describe" },
  { word: "Loud", board: "Describe" },
  { word: "Quiet", board: "Describe" },
  { word: "Right", board: "Describe" },
  { word: "Wrong", board: "Describe" },
  { word: "Best", board: "Describe" },
  { word: "Worst", board: "Describe" },
  { word: "Same", board: "Describe" },
  { word: "Different", board: "Describe" },
  { word: "Awesome", board: "Describe" },
  { word: "New", board: "Describe" },
  { word: "Old", board: "Describe" },
  { word: "Easy", board: "Describe" },
  { word: "Hard", board: "Describe" },
  { word: "Clean", board: "Describe" },
  { word: "Dirty", board: "Describe" },
  { word: "Small", board: "Describe" },
  { word: "Medium", board: "Describe" },
  { word: "Large", board: "Describe" },
  { word: "First", board: "Describe" },
  { word: "Last", board: "Describe" },
  { word: "High", board: "Describe" },
  { word: "Low", board: "Describe" },
  { word: "Young", board: "Describe" },
  { word: "Few", board: "Describe" },
  { word: "Many", board: "Describe" },
  { word: "Soft", board: "Describe" },
  { word: "Together", board: "Describe" },
  { word: "Separate", board: "Describe" },
  { word: "Pain", board: "Describe" },
  { word: "Pretty", board: "Describe" },
  { word: "Ugly", board: "Describe" },
  { word: "Funny", board: "Describe" },
  { word: "Tired", board: "Describe" },
  { word: "Favorite", board: "Describe" },
  { word: "Hungry", board: "Help" },
  { word: "Thirsty", board: "Help" },
  { word: "Tired", board: "Help" },
  { word: "In Pain", board: "Help" },
  { word: "Overwhelmed", board: "Help" },
  { word: "Overstimulated", board: "Help" },
  { word: "I Am", board: "Help" },
  { word: "I Need To Leave", board: "Help" },
  { word: "I", board: "People" },
  { word: "Me", board: "People" },
  { word: "My", board: "People" },
  { word: "Mine", board: "People" },
  { word: "Friend", board: "People" },
  { word: "Family", board: "People" },
  { word: "You", board: "People" },
  { word: "Your", board: "People" },
  { word: "Yours", board: "People" },
  { word: "Boy", board: "People" },
  { word: "Man", board: "People" },
  { word: "He", board: "People" },
  { word: "Him", board: "People" },
  { word: "His", board: "People" },
  { word: "Girl", board: "People" },
  { word: "Woman", board: "People" },
  { word: "She", board: "People" },
  { word: "Her", board: "People" },
  { word: "Hers", board: "People" },
  { word: "They", board: "People" },
  { word: "Them", board: "People" },
  { word: "Theirs", board: "People" },
  { word: "Theirs", board: "People" },
  { word: "People", board: "People" },
  { word: "Pet", board: "People" },
  { word: "Boss", board: "People" },
  { word: "Acquaintance", board: "People" },
  { word: "Coworker", board: "People" },
  { word: "Baby", board: "People" },
  { word: "Child", board: "People" },
  { word: "In", board: "Places" },
  { word: "Out", board: "Places" },
  { word: "Inside", board: "Places" },
  { word: "Outside", board: "Places" },
  { word: "On", board: "Places" },
  { word: "Home", board: "Places" },
  { word: "Store", board: "Places" },
  { word: "Work", board: "Places" },
  { word: "School", board: "Places" },
  { word: "Can You?", board: "Questions" },
  { word: "Can You Help?", board: "Questions" },
  { word: "When?", board: "Questions" },
  { word: "Why?", board: "Questions" },
  { word: "What?", board: "Questions" },
  { word: "Who?", board: "Questions" },
  { word: "What’S The Weather?", board: "Questions" },
  { word: "When?", board: "Questions" },
  { word: "How Long?", board: "Questions" },
  { word: "How Many?", board: "Questions" },
  { word: "Where?", board: "Questions" },
  { word: "Which?", board: "Questions" },
  { word: "Can I?", board: "Questions" },
  { word: "How Much", board: "Questions" },
  { word: "What Time Is It?", board: "Questions" },
  { word: "Do You Want It?", board: "Questions" },
  { word: "In Front", board: "ShortWords" },
  { word: "With", board: "ShortWords" },
  { word: "Between", board: "ShortWords" },
  { word: "Too", board: "ShortWords" },
  { word: "Behind", board: "ShortWords" },
  { word: "About", board: "ShortWords" },
  { word: "On", board: "ShortWords" },
  { word: "Off", board: "ShortWords" },
  { word: "End", board: "ShortWords" },
  { word: "Next", board: "ShortWords" },
  { word: "At", board: "ShortWords" },
  { word: "Or", board: "ShortWords" },
  { word: "And", board: "ShortWords" },
  { word: "For", board: "ShortWords" },
  { word: "A", board: "ShortWords" },
  { word: "With", board: "ShortWords" },
  { word: "Nothing", board: "ShortWords" },
  { word: "Everything", board: "ShortWords" },
  { word: "Phone", board: "Things" },
  { word: "Wallet", board: "Things" },
  { word: "Keys", board: "Things" },
  { word: "Headphones", board: "Things" },
  { word: "Today", board: "Time" },
  { word: "Tomorrow", board: "Time" },
  { word: "Yesterday", board: "Time" },
  { word: "Now", board: "Time" },
  { word: "Later", board: "Time" },
  { word: "1", board: "Time" },
  { word: "2", board: "Time" },
  { word: "3", board: "Time" },
  { word: "4", board: "Time" },
  { word: "5", board: "Time" },
  { word: "6", board: "Time" },
  { word: "7", board: "Time" },
  { word: "8", board: "Time" },
  { word: "9", board: "Time" },
  { word: "10", board: "Time" },
  { word: "11", board: "Time" },
  { word: "12", board: "Time" },
  { word: "O’Clock", board: "Time" },
  { word: "A.M.", board: "Time" },
  { word: "P.M.", board: "Time" },
  { word: "15", board: "Time" },
  { word: "30", board: "Time" },
  { word: "45", board: "Time" },
  { word: "Sunday", board: "Time" },
  { word: "Monday", board: "Time" },
  { word: "Tuesday", board: "Time" },
  { word: "Wednesday", board: "Time" },
  { word: "Thursday", board: "Time" },
  { word: "Friday", board: "Time" },
  { word: "Saturday", board: "Time" },
  { word: "Morning", board: "Time" },
  { word: "Night", board: "Time" },
];
